name: Version Check

on:
  pull_request:
    types:
      - synchronize

jobs:
  version_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version from VERSION file
        id: get_current_version
        run: |
          echo "::set-output name=version::$(cat VERSION)"
        shell: bash

      - name: Get proposed version from pull request
        id: get_proposed_version
        run: |
          pr_branch="$(echo ${{ github.event.pull_request.head.ref }})"
          git fetch origin "refs/pull/${{ github.event.pull_request.number }}/merge"
          proposed_version="$(git show FETCH_HEAD:VERSION)"
          echo "::set-output name=version::${proposed_version}"
        shell: bash

      - name: Check if versions match
        id: check_version
        run: |
          if [ "${{ steps.get_current_version.outputs.version }}" != "${{ steps.get_proposed_version.outputs.version }}" ]; then
            echo "Version has been updated. PR is allowed to merge."
          else
            echo "Version has not been updated. PR cannot merge."
            exit 1
          fi
        shell: bash
